Repository luxonis/depthai-viewer, pull requests merged in 2023-12, with the labels that each got.

#35 OAK D SR POE and some reliability improvements
  .gitignore
  Cargo.lock
  Cargo.toml
  api.py
  crates/re_viewer/src/depthai/dependency_installer.rs
  crates/re_viewer/src/depthai/depthai.rs
  crates/re_viewer/src/ui/auto_layout.rs
  crates/re_viewer/src/ui/device_settings_panel.rs
  crates/re_viewer/src/ui/selection_panel.rs
  crates/re_viewer/src/ui/space_view.rs
  crates/re_viewer/src/ui/space_view_heuristics.rs
  crates/re_viewer/src/ui/view_spatial/scene/scene_part/images.rs
  rerun_py/depthai_viewer/_backend/.gitignore
  rerun_py/depthai_viewer/_backend/device.py
  rerun_py/depthai_viewer/_backend/device_configuration.py
  rerun_py/depthai_viewer/_backend/main.py
  rerun_py/depthai_viewer/_backend/packet_handler.py
  rerun_py/depthai_viewer/_backend/topic.py
  rerun_py/depthai_viewer/install_requirements.py
  rerun_py/depthai_viewer/requirements.txt
  rust-toolchain
Labels: 📺 re_viewer

#36 UI changes
  crates/re_ui/src/lib.rs
  crates/re_viewer/src/app.rs
  crates/re_viewer/src/depthai/dependency_installer.rs
  crates/re_viewer/src/native.rs
  crates/re_viewer/src/ui/blueprint.rs
  crates/re_viewer/src/ui/device_settings_panel.rs
  crates/re_viewer/src/ui/stats_panel.rs
  crates/re_viewer/src/ui/viewport.rs
  rerun_py/depthai_viewer/_backend/device.py
  rerun_py/depthai_viewer/_backend/device_configuration.py
  rerun_py/depthai_viewer/_backend/packet_handler.py
  rerun_py/depthai_viewer/install_requirements.py
Labels: ui

#37 Release 0.1.5
  .gitignore
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  api.py
  crates/re_ui/src/lib.rs
  crates/re_viewer/src/app.rs
  crates/re_viewer/src/depthai/dependency_installer.rs
  crates/re_viewer/src/depthai/depthai.rs
  crates/re_viewer/src/native.rs
  crates/re_viewer/src/ui/auto_layout.rs
  crates/re_viewer/src/ui/blueprint.rs
  crates/re_viewer/src/ui/device_settings_panel.rs
  crates/re_viewer/src/ui/selection_panel.rs
  crates/re_viewer/src/ui/space_view.rs
  crates/re_viewer/src/ui/space_view_heuristics.rs
  crates/re_viewer/src/ui/stats_panel.rs
  crates/re_viewer/src/ui/view_spatial/scene/scene_part/images.rs
  crates/re_viewer/src/ui/viewport.rs
  rerun_py/depthai_viewer/_backend/.gitignore
  rerun_py/depthai_viewer/_backend/device.py
  rerun_py/depthai_viewer/_backend/device_configuration.py
  rerun_py/depthai_viewer/_backend/main.py
  rerun_py/depthai_viewer/_backend/packet_handler.py
  rerun_py/depthai_viewer/_backend/topic.py
  rerun_py/depthai_viewer/install_requirements.py
  rerun_py/depthai_viewer/requirements.txt
  rust-toolchain
Labels: ⛴ release
